--liquibase formatted sql
--changeset author:aquerr

CREATE TABLE IF NOT EXISTS aswg_authority (
  id IDENTITY PRIMARY KEY,
  code VARCHAR(50)    NOT NULL
);

INSERT INTO aswg_authority (id, code)
VALUES
(1, 'SERVER_START_STOP'),
(2, 'CONSOLE_LOGS_VIEW'),
(3, 'GENERAL_SETTINGS_VIEW'),
(4, 'GENERAL_SETTINGS_SAVE'),
(5, 'SECURITY_SETTINGS_VIEW'),
(6, 'SECURITY_SETTINGS_SAVE'),
(7, 'NETWORK_SETTINGS_VIEW'),
(8, 'NETWORK_SETTINGS_SAVE'),
(9, 'MODS_VIEW'),
(10, 'MODS_DELETE'),
(11, 'MODS_UPDATE'),
(12, 'MODS_UPLOAD'),
(13, 'MOD_SETTINGS_VIEW'),
(14, 'MOD_SETTINGS_ADD'),
(15, 'MOD_SETTINGS_DELETE'),
(16, 'MOD_SETTINGS_UPDATE'),
(17, 'MISSIONS_VIEW'),
(18, 'MISSIONS_ADD'),
(19, 'MISSIONS_DELETE'),
(20, 'MISSIONS_UPDATE'),
(21, 'MISSIONS_UPLOAD'),
(22, 'DIFFICULTY_VIEW'),
(23, 'DIFFICULTY_ADD'),
(24, 'DIFFICULTY_DELETE'),
(25, 'DIFFICULTY_UPDATE'),
(26, 'WORKSHOP_INSTALL'),
(27, 'USERS_VIEW'),
(28, 'USERS_ADD'),
(29, 'USERS_UPDATE'),
(30, 'USERS_DELETE'),
(31, 'MOD_PRESETS_VIEW'),
(32, 'MOD_PRESETS_ADD'),
(33, 'MOD_PRESETS_DELETE'),
(34, 'MOD_PRESETS_SELECT');